//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financier
{
    using System;
    using System.Collections.Generic;
    
    public partial class deposit
    {
        public int sno { get; set; }
        public Nullable<decimal> Account_No { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> OldBalance { get; set; }
        public string Mode { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public string Date { get; set; }
    }
}
